# Generated by Django 4.1.7 on 2024-03-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verify',
        ),
    ]
