# Generated by Django 3.2.10 on 2024-09-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
